### ISSUE TITLE
dl.fbaipublicfiles.com download links error

### ISSUE THREAD

**Issue by jskim217** [brianhie/efficient-evolution#6]
Hello. I'm trying to run your great model. But the job keep stopping with the below error.
Should I download each model and run the job?
----------------------------------------------------------

Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm1v_t33_650M_UR90S_1.pt" to /home/jisun/.cache/torch/hub/checkpoints/esm1v_t33_650M_UR90S_1.pt
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 1414, in connect
    super().connect()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/http/client.py", line 918, in connect
    self.sock = self._create_connection(
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by brianhie** [comment]
Hi @jskim217, can you check if your internet connection can hit that URL? E.g., https://dl.fbaipublicfiles.com/fair-esm/models/esm1v_t33_650M_UR90S_1.pt is still working for me.

**Comment by jskim217** [comment]
Hello Brian.

Thanks for responding.

The link is working when I input the command in the terminal in the server
I have been using. But they show the error when I submit the job including
the command.
[image: image.png]

Furthermore, the link (
https://dl.fbaipublicfiles.com/fair-esm/models/esm1b_t33_650M_UR50S-contact-regression.pt)
does not work.
[image: image.png]

Please advise if you have any solutions.

Best regards,
Jisun Kim

ᐧ

2023년 2월 1일 (수) 오후 5:05, Brian Hie ***@***.***>님이 작성:

**Comment by brianhie** [comment]
Does your cluster have internet access? Try download (and caching) the models locally beforehand, and then submit the jobs to the cluster.

**Comment by jskim217** [comment]
Okay, that's what I'm trying to do. Thanks for your help.
Have a good rest of the day.

Best regards,
Jisun Kim
ᐧ

2023년 2월 1일 (수) 오후 5:22, Brian Hie ***@***.***>님이 작성:

**Comment by brianhie** [comment]
Will close issue, feel free to reopen if there the root cause is an error.
